### ISSUE TITLE
Any hope to have this further developed? Net 7 for example?

### ISSUE THREAD

**Issue by mdelgadov** [Redth/Maui.UITesting#25]
I tried to implement your nice package but my project is already running in .Net 7 and was more pain than pleasure. Had to abandon.

Was wondering if you have any plans to port it to .Net7 or have an option for UI test instead?

Thanks in advance

**Comment by kfrancis** [comment]
Interested here as well. Started playing with this and this is so far about the only solution, even though it's not fully baked. Any thoughts about continuing?

**Comment by mdelgadov** [comment]
Judging for the intense discussion on the topic, Redth does not give a retromingent rat's arse.
